### PR TITLE
Add dll files  and annotation enhancement to include directories

### PR DESCRIPTION
**Pull request by PMehrfeld**
as discussed in #2 and #3

### CODE REVIEW

**Comment by tbeu** [comment]
About 871d6fccb4b038b69f8b06d011364264809aa5f3: I'd like to stick with netcdf 4.3.3.1 pre-built binaries for the following reasons
 * the pre-built binaries require the VS 2013 redistributable, but ncDataReader2.lib and ITI_ncDataReader2.dll are built with VS2010.
 * netcdf pre-built 4.3.3.1 binaries uses hdf5 1.8, wheras netcdf 4.4 uses hdf5 1.10. There are known performance and compatibility issues in hdf 1.10.

Two options (for me) here:
 * Add the pre-built binaries from the netcdf 4.3.3.1 package. Easy to do.
 * Build netcdf 4.4 with hdf5 1.8 on VS 2010. this requires some effort.

So if it is OK for you, I'd simply would add the binaries from the netcdf 4.3.3.1 binary distribution.

**Comment by tbeu** [comment]
About f39385a668d2df9ef1bc042cc5fe8be9014cc7c1: According to the MLS 3.3 rev1, section 12.9.4 the IncludeDirectory and LibraryDirectory you added are the default ones and need not be specified. Do you really require these annotations for your Modelica tool? Additionally, __iti_dllDirectory is not defined by SimulationX.

**Comment by PMehrfeld** [comment]
I have replaced dll files with the ones from netCDF 4.3.3.1. Still works. But we need these files, otherwise compilation aborts.
You are absolutely right. The suffix `...Directory` is not needed in the annotation. I reverted this.

**Comment by tbeu** [comment]
Thanks, merged manually.

**Pull request closed without merging**
